const envGQL = require("env.gql");

const typeDefs = `
    input Config {
      NEO4J_URL: String!
      NEO4J_USER: String!
      NEO4J_PASSWORD: String!
      REDIS_HOST: String!
      REDIS_PORT: Int!
      REDIS_RECEIVER_DEPLOY_QUEUE: String!
      REDIS_RECEIVER_DEPLOYED_QUEUE: String!
      REDIS_RECEIVER_DB: Int!
      WEB3_HTTP_PROVIDER: String!
      TRANSACTION_SIGNER_PRIVATE_KEY: String!
      TRANSACTION_SIGNER_PUBLIC_KEY: String!
      BANK_CONTRACT_ADDRESS: String!
    }
`;

const {
  NEO4J_URL,
  NEO4J_USER,
  NEO4J_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_RECEIVER_DEPLOY_QUEUE,
  REDIS_RECEIVER_DEPLOYED_QUEUE,
  REDIS_RECEIVER_DB,
  WEB3_HTTP_PROVIDER,
  TRANSACTION_SIGNER_PRIVATE_KEY,
  TRANSACTION_SIGNER_PUBLIC_KEY,
  BANK_CONTRACT_ADDRESS,
} = envGQL({ typeDefs });

module.exports = {
  NEO4J_URL,
  NEO4J_USER,
  NEO4J_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_RECEIVER_DEPLOY_QUEUE,
  REDIS_RECEIVER_DEPLOYED_QUEUE,
  REDIS_RECEIVER_DB,
  WEB3_HTTP_PROVIDER,
  TRANSACTION_SIGNER_PRIVATE_KEY,
  TRANSACTION_SIGNER_PUBLIC_KEY,
  BANK_CONTRACT_ADDRESS,
};
