const envGQL = require("env.gql");

const typeDefs = `
    input Config {
        SERVER_PORT: Int!
        NEO4J_URL: String!
        NEO4J_USER: String!
        NEO4J_PASSWORD: String!
        REDIS_HOST: String!
        REDIS_PORT: Int!
        REDIS_RECEIVER_DEPLOY_QUEUE: String!
        REDIS_RECEIVER_DB: Int!
        REDIS_WITHDRAWER_QUEUE: String!
        REDIS_WITHDRAWER_DB: Int!
    }
`;

const {
  SERVER_PORT,
  NEO4J_URL,
  NEO4J_USER,
  NEO4J_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_RECEIVER_DEPLOY_QUEUE,
  REDIS_RECEIVER_DB,
  REDIS_WITHDRAWER_QUEUE,
  REDIS_WITHDRAWER_DB,
} = envGQL({ typeDefs });

module.exports = {
  SERVER_PORT,
  NEO4J_URL,
  NEO4J_USER,
  NEO4J_PASSWORD,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_RECEIVER_DEPLOY_QUEUE,
  REDIS_RECEIVER_DB,
  REDIS_WITHDRAWER_QUEUE,
  REDIS_WITHDRAWER_DB,
};
